# Generated by Django 6.0.3 on 2026-03-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWaterSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('roof_area', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('runoff_coefficient', models.FloatField(default=0.8)),
                ('water_saved', models.FloatField(help_text='Liters per year')),
                ('money_saved', models.FloatField(help_text='INR per year')),
                ('badge', models.CharField(max_length=64)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_water_savings',
                'ordering': ['-calculation_date'],
            },
        ),
    ]
