# Generated by Django 6.0.3 on 2026-03-31 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_watertank_floodpredictionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorewellEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('location', models.CharField(max_length=200)),
                ('annual_rainfall_mm', models.FloatField()),
                ('region_type', models.CharField(max_length=20)),
                ('soil_type', models.CharField(max_length=20)),
                ('min_depth_feet', models.IntegerField()),
                ('max_depth_feet', models.IntegerField()),
                ('recommended_depth_feet', models.IntegerField()),
                ('confidence_level', models.FloatField()),
                ('water_availability', models.CharField(max_length=20)),
                ('estimated_yield_lph', models.IntegerField()),
                ('reasoning', models.TextField()),
                ('cost_estimate_min', models.IntegerField()),
                ('cost_estimate_max', models.IntegerField()),
                ('estimation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borewell_estimations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'borewell_estimation',
                'ordering': ['-estimation_time'],
            },
        ),
    ]
